FINAL SEARCH TOOL

1. insert minimum and maximum bpm values in 'lowbpm'and 'highbpm'  (sometimes they appear as decimals so having these at least 1 or 2 numbers apart)

2. insert tonality in 'key', making sure to keep the quotation marks around your value

3. run line 1 (shift enter)
4. run line 2 (shift enter), and view your list of options!

In [142]:
lowbpm = 70
highbpm = 79
key = "Am"

In [143]:
finaldf.loc[(finaldf['@AverageBpm'] >lowbpm) & (finaldf['@AverageBpm']<highbpm) & (finaldf['@Tonality'] == key)]

             @Name  @AverageBpm @Tonality
310  Bih Get Nasty         76.5        Am
312     Quick Trip         72.0        Am
313  Marble Floors         75.5        Am

WORK BELOW:

______________________________________________________

IMPORTS:

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import xmltodict

DEFINING XML FILE PATH

In [18]:
xmll = '/content/drive/MyDrive/rekordboxcollection.xml'

MAKING A DICT FROM THE XML FILE USING XMLTODICT

In [24]:
rekorddict = xmltodict.parse(open(xmll).read())

In [ ]:
MAKING A DATAFRAME OUT OF THE PORTION OF THE DICT I WANT TO USE

MAKING A DATAFRAME OUT OF THE PORTION OF THE DICT I WANT TO USE

In [41]:
df = pd.DataFrame(rekorddict['DJ_PLAYLISTS']['COLLECTION']['TRACK'])

CHECKING DATAFRAME STRUCTURE

In [65]:
df.head(30)

,@TrackID,@Name,@Artist,@Composer,@Album,@Grouping,@Genre,@Kind,@Size,@TotalTime,...,@Comments,@PlayCount,@Rating,@Location,@Remixer,@Tonality,@Label,@Mix,TEMPO,POSITION_MARK
0,11326407,NOISE,,,,,,WAV File,1382226,5,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
1,121740190,SINEWAVE,,,,,,WAV File,1515258,5,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
2,157704080,SIREN,,,,,,WAV File,1941204,7,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
3,183686606,HORN,,,,,,WAV File,2010816,7,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
4,67569725,Demo Track 1,Loopmasters,,,,,MP3 File,6899624,172,...,Tracks by www.loopmasters.com,0,0,file://localhost/Users/evie/Music/PioneerDJ/De...,,,Loopmasters,,"{'@Inizio': '0.025', '@Bpm': '128.00', '@Metro...",NaN
5,93570087,Demo Track 2,Loopmasters,,,,,MP3 File,5124342,128,...,Tracks by www.loopmasters.com,0,0,file://localhost/Users/evie/Music/PioneerDJ/De...,,,Loopmasters,,"[{'@Inizio': '0.025', '@Bpm': '120.00', '@Metr...",NaN
6,58238997,CYMBAL,,,,,,WAV File,543576,2,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
7,24402705,SHORT BOOM,Loopmasters,,,,,WAV File,727752,2,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
8,246340586,LET'S GO,Loopmasters,,,,,WAV File,1002802,3,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
9,116036122,NEEDLE SCRATCH NOISE,,,,,,WAV File,543590,2,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
10,191483179,CLAP,,,,,,WAV File,203884,0,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
11,254878103,SNARE8,,,,,,WAV File,135948,0,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
12,223208217,HORN,,,,,,WAV File,1621228,6,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
13,263923815,SNARE9,,,,,,WAV File,186906,0,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
14,63742830,REWIND,,,,,,WAV File,1494288,5,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
15,204700410,BOOM DOWN LIFTER2,Loopmasters,,,,,WAV File,1639462,9,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
16,178699470,NOISE DOWN LIFTER1,Loopmasters,,,,,WAV File,1297040,4,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
17,80717563,IMPACT KICK,Loopmasters,,,,,WAV File,1459146,5,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
18,143372005,NOISE DOWN LIFTER2,Loopmasters,,,,,WAV File,1378094,5,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
19,146878921,SNARE,Loopmasters,,,,,WAV File,486444,1,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
20,141117458,BOOM DOWN LIFTER1,Loopmasters,,,,,WAV File,1297038,4,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
21,202671818,CLASH CYMBAL,,,,,,WAV File,1155024,4,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
22,44026076,IMPACT SNARE,Loopmasters,,,,,WAV File,1489766,5,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
23,252474837,SHORT BOOM,Loopmasters,,,,,WAV File,652554,2,...,,0,0,file://localhost/Users/evie/Music/rekordbox/Sa...,,,,,NaN,NaN
24,206695724,all 2s,2hollis,,,,,Unknown Format,0,167,...,,1,0,file://localhostsoundcloud:tracks:1496404216,,Cm,,,"{'@Inizio': '0.327', '@Bpm': '137.95', '@Metro...","[{'@Name': '', '@Type': '0', '@Start': '152.55..."
25,198395870,plaster,2hollis,,,,Electronic,Unknown Format,0,260,...,,1,0,file://localhostsoundcloud:tracks:1346042086,,B,,,"{'@Inizio': '0.000', '@Bpm': '140.00', '@Metro...","[{'@Name': '', '@Type': '0', '@Start': '21.857..."
26,133936996,THE HELLP - SINAMEN / PEROXIDE,j. hayes,,,,,Unknown Format,0,266,...,,1,0,file://localhostsoundcloud:tracks:519024492,,Cm,,,"[{'@Inizio': '0.032', '@Bpm': '88.20', '@Metro...","{'@Name': '', '@Type': '0', '@Start': '73.500'..."
27,102574362,the hellp - hotfun 22,xxxtalll,,,,Electronic,Unknown Format,0,112,...,,1,0,file://localhostsoundcloud:tracks:941645719,,Cm,,,"{'@Inizio': '0.225', '@Bpm': '125.04', '@Metro...","[{'@Name': '', '@Type': '0', '@Start': '92.834..."
28,191702017,might be crazy,dltzk,,frailty scraps,,,MP3 File,3375422,148,...,,1,0,file://localhost/Users/evie/Music/Music/Media....,,,,,"{'@Inizio': '0.446', '@Bpm': '85.25', '@Metro'...",NaN
29,149715198,Everything Is Embarrassing,,,,,,MP3 File,5999941,249,...,,3,0,file://localhost/Users/evie/Music/Music/Media....,,C,,,"[{'@Inizio': '0.259', '@Bpm': '117.16', '@Metr...","{'@Name': '', '@Type': '0', '@Start': '10.502'..."

DELETING UNNECCESARY STOCK LOOP DATA

In [67]:
cleandf=df[24:333]

CHECKING COLUMNS

In [72]:
cleandf.columns

Index(['@TrackID', '@Name', '@Artist', '@Composer', '@Album', '@Grouping',
       '@Genre', '@Kind', '@Size', '@TotalTime', '@DiscNumber', '@TrackNumber',
       '@Year', '@AverageBpm', '@DateAdded', '@BitRate', '@SampleRate',
       '@Comments', '@PlayCount', '@Rating', '@Location', '@Remixer',
       '@Tonality', '@Label', '@Mix', 'TEMPO', 'POSITION_MARK'],
      dtype='object')

NEW DATAFRAME USING ONLY COLUMNS I NEED

In [94]:
finaldf = cleandf[['@Name','@AverageBpm','@Tonality']]

CHECKING NEW DATAFRAME

In [95]:
finaldf.head()

                             @Name @AverageBpm @Tonality
24                          all 2s      137.95        Cm
25                         plaster      140.00         B
26  THE HELLP - SINAMEN / PEROXIDE       88.20        Cm
27           the hellp - hotfun 22      125.04        Cm
28                  might be crazy       85.25

CHECKING TO SEE IF BPM IS A FLOAT

In [97]:
finaldf.dtypes

@Name          object
@AverageBpm    object
@Tonality      object
dtype: object

CHANGING BPM TABLE TO FLOATS TO ALLOW COMPARISONS

In [101]:
finaldf['@AverageBpm'] = pd.to_numeric(finaldf['@AverageBpm'],errors='coerce')

/tmp/ipykernel_1131/3820462496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finaldf['@AverageBpm'] = pd.to_numeric(finaldf['@AverageBpm'],errors='coerce')

TESTING....

In [116]:
finaldf.loc[(finaldf['@AverageBpm'] >140) & (finaldf['@AverageBpm']<150) & (finaldf['@Tonality'] == 'Cm')]

                   @Name  @AverageBpm @Tonality
38                 light        141.0        Cm
81            RIP Corbin        145.0        Cm
84  Dead First Prettifun        147.0        Cm